=== gulwator/FOQH34_XMLGyak/XMLTaskFOQH34/XMLSchemaFOQH34.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/XMLSchemaFOQH34" elementFormDefault="qualified">
	<xs:element name="adatbazis">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="vasarlo" type="vasarloTipus" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="termek" type="termekTipus" maxOccurs="unbounded"/>
				<xs:element name="vasarlas" type="vasarlasTipus" maxOccurs="unbounded"/>
				<xs:element name="tkartya" type="tkartyaTipus" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		
		<xs:key name="vasarloKulcs">
		<xs:selector xpath="vasarlo"/>
		<xs:field xpath="@id" />
		</xs:key>
		<xs:key name="tkartyaKulcs">
		<xs:selector xpath="tkartya"/>
		<xs:field xpath="@id" />
		</xs:key>
		<xs:key name="termekKulcs">
		<xs:selector xpath="termek"/>
		<xs:field xpath="@id" />
		</xs:key>
		<xs:key name="vasarlasKulcs">
		<xs:selector xpath="vasarlas"/>
		<xs:field xpath="@id" />
		</xs:key>
		
		<xs:keyref name="vasarlas-termek" refer="termekKulcs">
		<xs:selector xpath="vasarlas/tKod"/>
		<xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="vasarlas-vasarlo" refer="vasarloKulcs">
		<xs:selector xpath="vasarlas/vid"/>
		<xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="vasarlo-tkartya" refer="tkartyaKulcs">
		<xs:selector xpath="vasarlo/tkartyaid"/>
		<xs:field xpath="."/>
		</xs:keyref>
	</xs:element>
	<xs:complexType name="vasarloTipus">
		<xs:sequence>		
			<xs:element name="lakcim" type="lakcimTipus" />
			<xs:element name="nev" type="nev"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required" />
	</xs:complexType>
	
	<xs:complexType name="lakcimTipus">
		<xs:sequence>
			<xs:element name="iranyitoSzam" type="iranyitoSzam"/>
			<xs:element name="varos" type="varos"/>
			<xs:element name="utca" type="utca"/>
			<xs:element name="hazszam" type="hazszam"/>
		</xs:sequence>
	</xs:complexType> 
	
	<xs:simpleType name="iranyitoSzam">
		<xs:restriction base="xs:positiveInteger"/>
	</xs:simpleType>
	
	<xs:simpleType name="varos">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	
	<xs:simpleType name="utca">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	
	<xs:simpleType name="hazszam">
		<xs:restriction base="xs:positiveInteger"/>
	</xs:simpleType>
	
	<xs:simpleType name="nev">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	
	<xs:complexType name="termekTipus">
		<xs:sequence>
			<xs:element name="szarmazasiOrszag" type="xs:string"/>
			<xs:element name="latinNev" type="xs:string"/>
			<xs:element name="ar" type="xs:positiveInteger"/>
			<xs:element name="aruMegnevezes" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required" />
	</xs:complexType>
	<xs:complexType name="tkartyaTipus">
		<xs:sequence>
			<xs:element name="szint" type="xs:string"/>
			<xs:element name="kedvezmeny" type="xs:positiveInteger"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required" />
	</xs:complexType>
	<xs:complexType name="vasarlasTipus">
		<xs:sequence>
			<xs:element name="vid" type="xs:string"/>
			<xs:element name="darab" type="xs:string"/>
			<xs:element name="tKod" type="xs:string"/>
			<xs:element name="idopont" type="xs:date"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required" />
	</xs:complexType>
</xs:schema>

=== gulwator/FOQH34_XMLGyak/XMLTaskFOQH34/XMLfoqh34.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<adatbazis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaFOQH34.xsd">
    	
  
  <vasarlo id="V12">
        		
    
    <lakcim>
            			
      
      <iranyitoSzam>3535</iranyitoSzam>
            			
      
      <varos>Miskolc</varos>
            			
      
      <utca>Hegyalja utca</utca>
            			
      
      <hazszam>15</hazszam>
            		
    
    </lakcim>
        		
    
    <nev>Kertesz Laszlo</nev>
        	
  
  </vasarlo>
    	
  
  <vasarlo id="V13">
        		
    
    <lakcim>
            			
      
      <iranyitoSzam>3516</iranyitoSzam>
            			
      
      <varos>Miskolc</varos>
            			
      
      <utca>Csermak Antal utca</utca>
            			
      
      <hazszam>41</hazszam>
            		
    
    </lakcim>
        		
    
    <nev>Toth Levente</nev>
        	
  
  </vasarlo>
    	
  
  <termek id="T01">
        		
    
    <szarmazasiOrszag>Hollandia</szarmazasiOrszag>
        		
    
    <latinNev>Rosa</latinNev>
        		
    
    <ar>850</ar>
        		
    
    <aruMegnevezes>Voros rozsa</aruMegnevezes>
        	
  
  </termek>
    	
  
  <termek id="T02">
        		
    
    <szarmazasiOrszag>Magyar</szarmazasiOrszag>
        		
    
    <latinNev>-</latinNev>
        		
    
    <ar>1200</ar>
        		
    
    <aruMegnevezes>illat gyertya</aruMegnevezes>
        	
  
  </termek>
    	
	
  
  <vasarlas id="S01">
        		
    
    <vid>12</vid>
        		
    		
    
    <darab>10</darab>
        		
    
    <tKod>01</tKod>
        		
    
    <idopont>2022-12-05</idopont>
        	
  
  </vasarlas>
    

</adatbazis>
